print ("-_-_- Verificador de ordem de números do Omega -_-_-")
print()
num = []
num.append(float(input("Digite um número: ")))
num.append(float(input("Digite um número: ")))
num.append(float(input("Digite um número: ")))
print()
num.sort()
print(num)
print()
print()